---
- name: Copia o arquivo deb
  copy:
     src: metricbeat-7.14.2-amd64.deb
     dest: /tmp/metricbeat-7.14.2-amd64.deb
     
- name: Instala o pacote DEB.
  apt:
     deb: /tmp/metricbeat-7.14.2-amd64.deb
           
- name: Copia o arquivo de configuração
  template: src=metricbeat.yml.j2 dest=/etc/metricbeat/metricbeat.yml owner=root group=root mode=0644 backup=yes

- name: Habilitar o modulo system
  shell: metricbeat modules enable system

- name: Instala os modulos do mtricbeat
  shell: metricbeat setup
  
- name: Habilita e Inicia o Serviço
  service: name=metricbeat state=started enabled=yes
