---
# Variaveis Elasticsearch
es_version: "7.3.0"
es_use_snapshot_release: false
es_enable_xpack: true
es_name: "elasticsearch"
es_version_lock: false
es_use_repository: true
es_add_repository: true
es_templates_fileglob: "files/templates-{{ es_major_version }}/*.json"
es_repo_base: "https://artifacts.elastic.co"
es_apt_key: "{{ es_repo_base }}/GPG-KEY-elasticsearch"
es_apt_url: "deb {{ es_repo_base }}/packages/{{ es_repo_name }}/apt stable main"
es_apt_url_old: "deb http://packages.elastic.co/elasticsearch/{{ es_repo_name }}/debian stable main"
es_start_service: true
es_java_install: "{{ false if (es_version is version_compare('7.0.0', '>=')) else true }}"
update_java: false
es_restart_on_change: true
es_plugins_reinstall: false
es_templates: false
es_user: elasticsearch
es_group: elasticsearch
es_config: {}
es_config_log4j2: log4j2.properties.j2
es_conf_dir: "/etc/elasticsearch"
es_pid_dir: "/var/run/elasticsearch"
es_data_dirs:
  - "/var/lib/elasticsearch"
es_log_dir: "/var/log/elasticsearch"
es_action_auto_create_index: true
es_max_open_files: 65536
es_max_threads: "{{ 2048 if ( es_version is version_compare('6.0.0', '<')) else 8192 }}"
es_max_map_count: 262144
es_allow_downgrades: false
es_xpack_features: []
es_api_host: "localhost"
es_api_port: 9200
es_debian_startup_timeout: 10
es_jvm_custom_parameters: ''

# Variaveis Kibana
kibana_version: "7.x"
kibana_package: kibana
kibana_package_state: present
kibana_service_state: started
kibana_service_enabled: true
kibana_config_template: kibana.yml.j2
kibana_config_file_path: /etc/kibana/kibana.yml
kibana_server_port: 5601
kibana_server_host: "0.0.0.0"
kibana_host: localhost # Para uso do filebeat
kibana_elasticsearch_url: "http://localhost:9200"
kibana_elasticsearch_username: ""
kibana_elasticsearch_password: ""

# Variaveis Logstash
logstash_version: '7.x'
logstash_listen_port_beats: 5044
logstash_host: localhost # para uso do filebeat
logstash_elasticsearch_hosts:
  - http://localhost:9200
logstash_local_syslog_path: /var/log/syslog
logstash_monitor_local_syslog: true
logstash_dir: /usr/share/logstash
logstash_ssl_dir: /etc/pki/logstash
logstash_ssl_certificate_file: ""
logstash_ssl_key_file: ""
logstash_enabled_on_boot: true
logstash_install_plugins:
  - logstash-input-beats
  - logstash-codec-multiline

# Variaveis Filebeat
filebeat_version: 7.x
filebeat_create_config: true

filebeat_prospectors:
  - input_type: log
    paths:
      - "/var/log/*.log"

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "localhost:9200"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "localhost:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/servers/*/*/*/*/*
filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "false"

# Variaveis Rsyslog
rsyslog_user: syslog
rsyslog_path: '/var/log/servers'
rsyslog_server: localhost
tcp_port: 514
