---
- name: Verificar se grupo elasticsearch esta criado com id correto
  group:
    state: present
    name: "{{ es_group }}"
    system: yes
    gid: "{{ es_group_id }}"
  notify: restart elasticsearch

- name: Verificar se usuario elasticsearch esta criado com id correto
  user:
    state: present
    name: "{{ es_user }}"
    comment: elasticsearch system user
    system: yes
    createhome: no
    uid: "{{ es_user_id }}"
    group: "{{ es_group }}"
  notify: restart elasticsearch
