---
- name: Criar Diretorios
  become: yes
  file: path={{ item }} state=directory owner={{ es_user }} group={{ es_group }}
  with_items:
    - "{{ es_pid_dir }}"
    - "{{ es_log_dir }}"
    - "{{ es_conf_dir }}"
    - "{{ es_data_dirs }}"

- name: Copiar arquivos de configuração
  become: yes
  template: src=elasticsearch.yml.j2 dest={{ es_conf_dir }}/elasticsearch.yml owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  register: system_change
  notify: restart elasticsearch

- name: Copiar arquivos padrões
  become: yes
  template: src=elasticsearch.j2 dest={{ default_file }} mode=0644 force=yes
  notify: restart elasticsearch

#Copy the systemd specific file if systemd is installed
- when: use_system_d and m_lock_enabled
  become: yes
  block:
    - name: Make sure destination dir exists
      file: path={{ sysd_config_file | dirname }} state=directory mode=0755
  
    - name: Copy specific ElasticSearch Systemd config file
      ini_file: path={{ sysd_config_file }} section=Service option=LimitMEMLOCK value=infinity mode=0644
      notify:
       - reload systemd configuration
       - restart elasticsearch

- name: Copiar logging.yml
  become: yes
  template: src={{ es_config_log4j2 }} dest={{ es_conf_dir }}/log4j2.properties owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  notify: restart elasticsearch

- name: Copiar jvm.options
  become: yes
  template: src=jvm.options.j2 dest={{ es_conf_dir }}/jvm.options owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  notify: restart elasticsearch
