---
- set_fact: "es_major_version={{ es_version.split('.')[0] }}.x"
  when:
      - es_major_version is undefined

- name: Carregar variáveis para sistema {{ ansible_os_family }}
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
      - always

- name: Carregar variáveis específicas para ambiente {{ ansible_os_family }}
  include: compatibility-variables.yml
  tags:
      - always

- name: Checar parametros carregados
  include: elasticsearch-parameters.yml
  tags:
      - always

- name: Use snapshot da ultima release caso positivo
  include: snapshot-release.yml
  when: es_use_snapshot_release

- name: Carregar playbook de instalação do java
  include: java.yml
  when: es_java_install
  tags:
      - java

- name: Carregar playbook de instalação do elasticsearch
  include: elasticsearch.yml
  tags:
      - install

- name: Carregar configurações do elasticsearch-config.yml
  include: elasticsearch-config.yml  
  tags:
      - config
- name: Carregar plugins do elasticsearch-plugins.yml
  include: elasticsearch-plugins.yml
  when: es_plugins is defined or es_plugins_reinstall
  tags:
      - plugins

- name: Carregar módulos xpack/elasticsearch-xpack.yml se ativo
  include: xpack/elasticsearch-xpack.yml
  tags:
      - xpack

- name: flush handlers
  meta: flush_handlers

- name: Verificar se serviço está iniciado e ativo
  service:
    name: elasticsearch
    state: started
    enabled: yes
  when: es_start_service

- name: Esperar inicialização do Elasticsearch
  wait_for:
    host: "{{ es_api_host }}"
    port: "{{ es_api_port }}"
    delay: 5
    connect_timeout: 1
  when: es_restarted is defined and es_restarted.changed and es_start_service

- name: Alterar parametro manage_native_realm para false se definido
  set_fact: manage_native_realm=false

- name: Alterar manage_native_realm para true se definido
  set_fact: manage_native_realm=true
  when:
   - es_start_service
   - es_enable_xpack
   - (es_users is defined and es_users.native is defined) or (es_roles is defined and es_roles.native is defined)

- name: Esperar 15 segundos para inicio de Relm nativo
  command: sleep 15
  when: manage_native_realm

- name: Ativar licença
  include: ./xpack/security/elasticsearch-xpack-activation.yml
  when: es_start_service and es_enable_xpack and es_xpack_license is defined and es_xpack_license != ''

- name: Carregar playbook xpack/security/elasticsearch-security-native.yml
  include: ./xpack/security/elasticsearch-security-native.yml
  when: manage_native_realm

- name: Carregar playbook elasticsearch-template.yml
  include: elasticsearch-template.yml
  when: es_templates
  tags:
      - templates
