---
- name: Copiar configuração do Filebeat
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat

- name: Verificar se existe chave criada
  file:
    path: "{{ filebeat_ssl_dir }}"
    state: directory
  when: filebeat_ssl_key_file | bool

- name: Copiar chave e certificado SSL para o Filebeat
  copy:
    src: "{{ item }}"
    dest: "{{ filebeat_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ filebeat_ssl_key_file }}"
    - "{{ filebeat_ssl_certificate_file }}"
  notify: restart filebeat
  when:
    - filebeat_ssl_key_file | bool
    - filebeat_ssl_certificate_file | bool 
