---
- name: Copia o arquivo rpm
  copy:
     src: filebeat-7.14.2-x86_64.rpm
     dest: /tmp/filebeat-7.14.2-x86_64.rpm
     
- name: Instala o pacote RPM.
  yum:
     name: /tmp/filebeat-7.14.2-x86_64.rpm
     state: present
     
           
- name: Copia o arquivo de configuração
  template: src=filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml owner=root group=root mode=0644 backup=yes

- name: Habilitar o modulo system
  shell: filebeat modules enable system

- name: Habilita o modulo audit
  shell: filebeat modules enable auditd

- name: Instala os modulos do filebeat
  shell: filebeat setup
  
- name: Habilita e Inicia o Serviço
  service: name=filebeat state=started enabled=yes
