---
- hosts: elastic-prod-data
  become: yes
  become_method: sudo
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "producao-cluster"
      cluster.initial_master_nodes: ["pvlsede012","pvlsede013","pvlsede014"]
      discovery.seed_hosts: ["pvlsede012","pvlsede013","pvlsede014"]
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
#    es_plugins:
#     - plugin: ingest-attachment
