# Realiza a instalao de pacotes basicos no SO DEBIAN

---

- hosts: redmine-hlog
  gather_facts: yes
  become: yes
  become_user: root
  become_method: su
  tasks:


  - name: Update no SO
    shell: apt-get update -y

  - name: Instalando Pacotes basicos no Sistema Operacional Debian
    apt: name={{ item }} state=present
    with_items:
       - sudo
       - mlocate
       - ncdu

  - name: Update no SO
    shell: apt-get update -y